import { Platform, StyleSheet } from "react-native";
import { colors } from "@shared/theme/colors";

export default StyleSheet.create({
    container: {
        paddingHorizontal: 24,
        paddingTop: 8,
    },
    logoRow: {
        flexDirection: "row",
        justifyContent: "center",
        marginBottom: 40,
    },
    logoDark: { fontSize: 34, fontWeight: "800", color: colors.dark, letterSpacing: -0.5 },
    logoGreen: { fontSize: 34, fontWeight: "800", color: colors.primary, letterSpacing: -0.5 },
    title: { fontSize: 26, fontWeight: "800", color: colors.dark, marginBottom: 6 },
    subtitle: { fontSize: 14, color: colors.textSecondary, marginBottom: 24 },
    input: {
        backgroundColor: colors.surface,
        borderRadius: 14,
        paddingHorizontal: 18,
        paddingVertical: Platform.OS === "ios" ? 18 : 14,
        fontSize: 15,
        color: colors.dark,
        marginBottom: 14,
        borderWidth: 1,
        borderColor: colors.border,
    },
    passwordWrap: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: colors.surface,
        borderRadius: 14,
        paddingHorizontal: 18,
        borderWidth: 1,
        borderColor: colors.border,
        marginBottom: 8,
    },
    passwordInput: {
        flex: 1,
        paddingVertical: Platform.OS === "ios" ? 18 : 14,
        fontSize: 15,
        color: colors.dark,
    },
    toggleText: { color: colors.primary, fontWeight: "700", fontSize: 13 },
    error: { color: "#E5484D", fontSize: 13, marginTop: 6, marginBottom: 4 },
    primaryBtn: {
        backgroundColor: colors.primary,
        borderRadius: 14,
        paddingVertical: 17,
        alignItems: "center",
        justifyContent: "center",
        marginTop: 18,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.35,
        shadowRadius: 12,
        elevation: 4,
    },
    primaryBtnPressed: { backgroundColor: colors.primaryDark },
    primaryBtnDisabled: { opacity: 0.5, shadowOpacity: 0, elevation: 0 },
    primaryBtnText: { color: colors.white, fontSize: 16, fontWeight: "700" },
    switchRow: { marginTop: 22, alignItems: "center" },
    switchText: { color: colors.textSecondary, fontSize: 14 },
    switchAction: { color: colors.primary, fontWeight: "700" },

    dividerRow: { flexDirection: "row", alignItems: "center", marginVertical: 22 },
    line: { flex: 1, height: 1, backgroundColor: colors.divider },
    dividerText: { marginHorizontal: 12, color: colors.textSecondary, fontSize: 13 },
    socialBtn: {
        backgroundColor: colors.surface,
        borderRadius: 14,
        paddingVertical: 17,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 14,
        borderWidth: 1,
        borderColor: colors.border,
    },
    socialText: { color: colors.dark, fontSize: 15, fontWeight: "700" },
});